package com.zoowii.levelsql.protocol.mysql

object Capabilities {
    const val CLIENT_MYSQL: Long = 1
    const val FOUND_ROWS = (1 shl 1.toLong().toInt()).toLong()
    const val LONG_FLAG = (1 shl 2.toLong().toInt()).toLong()
    const val CONNECT_WITH_DB = (1 shl 3.toLong().toInt()).toLong()
    const val NO_SCHEMA = (1 shl 4.toLong().toInt()).toLong()
    const val COMPRESS = (1 shl 5.toLong().toInt()).toLong()
    const val ODBC = (1 shl 6.toLong().toInt()).toLong()
    const val LOCAL_FILES = (1 shl 7.toLong().toInt()).toLong()
    const val IGNORE_SPACE = (1 shl 8.toLong().toInt()).toLong()
    const val PROTOCOL_41 = (1 shl 9.toLong().toInt()).toLong()
    const val INTERACTIVE = (1 shl 10.toLong().toInt()).toLong()
    const val SSL = (1 shl 11.toLong().toInt()).toLong()
    const val IGNORE_SIGPIPE = (1 shl 12.toLong().toInt()).toLong()
    const val TRANSACTIONS = (1 shl 13.toLong().toInt()).toLong()
    const val RESERVED = (1 shl 14.toLong().toInt()).toLong()
    const val SECURE_CONNECTION = (1 shl 15.toLong().toInt()).toLong()
    const val MULTI_STATEMENTS = (1 shl 16.toLong().toInt()).toLong()
    const val MULTI_RESULTS = (1 shl 17.toLong().toInt()).toLong()
    const val PS_MULTI_RESULTS = (1 shl 18.toLong().toInt()).toLong()
    const val PLUGIN_AUTH = (1 shl 19.toLong().toInt()).toLong()
    const val CONNECT_ATTRS = (1 shl 20.toLong().toInt()).toLong()
    const val PLUGIN_AUTH_LENENC_DATA = (1 shl 21.toLong().toInt()).toLong()
    const val CAN_HANDLE_EXPIRED_PASSWORDS = (1 shl 22.toLong().toInt()).toLong()
    const val CLIENT_SESSION_TRACK = (1 shl 23.toLong().toInt()).toLong()
    const val CLIENT_DEPRECATE_EOF = (1 shl 24.toLong().toInt()).toLong()
    const val SSL_VERIFY_SERVER_CERT = (1 shl 30.toLong().toInt()).toLong()
    const val REMEMBER_OPTIONS = (1 shl 31.toLong().toInt()).toLong()
    const val MARIADB_CLIENT_PROGRESS = (1 shl 32.toLong().toInt()).toLong()
    const val MARIADB_CLIENT_COM_MULTI = (1 shl 33.toLong().toInt()).toLong()
    const val MARIADB_CLIENT_STMT_BULK_OPERATIONS = (1 shl 34.toLong().toInt()).toLong()
}